### ISSUE TITLE
whether this tool can solve the "bug" that the prometheus can't  officially support read data api from opentsdb?

### ISSUE THREAD

**Issue by zzqq0103** [barasher/prometheus-to-opentsdb#15]
whether this tool can solve the "bug" that the Prometheus can't officially support read data API from opentsdb?

**Comment by barasher** [comment]
Hi,
No, `prometheus-to-opentsdb` neither permits Prometheus to reads nor loads data from an Opentsdb cluster.
It extracts data from Prometheus and pushes it to Opentsdb.
